version: '3.9'

services:
  web:
    build: ./front
    ports:
      - "9092:9090"
    volumes:
      - /front/
    networks:
      - my-shared-network

  model:
    build: ./model_api
    volumes:
      - /model_api/models:/app/models
    networks:
      - my-shared-network

networks:
  my-shared-network:
