version: '3.9'

services:
  web:
    build: ./front
    privileged: true
    ports:
      - "8090:8080"
    volumes:
      - "./front/static/:/app/static"
      - "./front/templates/:/app/templates"
    networks:
      - my-shared-network

  model:
    build: ./model_api
    volumes:
      - "./model_api/models:/app/models"
    networks:
      - my-shared-network

networks:
  my-shared-network:
